name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :index:build
      - name: Test with Gradle
        run: ./gradlew :index:test
      - name: Spotbugs (on index main)
        run: ./gradlew :index:spotBugsMain
        continue-on-error: true
      - name: checkstyle (on index main)
        run: ./gradlew :index:checkstyleMain
        continue-on-error: true
